<?php 
/**
 * CoolMS2 Common Module (http://www.coolms.com/)
 *
 * @link      http://github.com/coolms/common for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsCommon;

// Set form fields classes and placeholders here
$this->fieldset->get('startDate')->setOption('twbs', [
    'col' => ['class' => 'col-xs-12 col-sm-6'],
    'endDate' => [
        'type' => 'formGroupElement',
        'content' => 'endDate',
        'order' => 9050,
        'placement' => 'append',
    ],
]);

$this->fieldset->get('endDate')->setOption('twbs', [
    'col' => ['class' => 'col-xs-12 col-sm-6'],
]);

?>
<?= $this->formCollection($this->fieldset, true, false);
